version: '1'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: 843556918706.dkr.ecr.us-west-2.amazonaws.com/mongo-image-repository:server # todo-server
    container_name: todo-node-server
    command: npm run start
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - PORT=3001
      - URI=mongodb://full-LoadB-13V2JDPTSMTFB-63353af261e3a4e6.elb.us-west-2.amazonaws.com:27017
    networks:
      - app-network
  mongo:
    image: 843556918706.dkr.ecr.us-west-2.amazonaws.com/mongo-image-repository:latest # mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: 843556918706.dkr.ecr.us-west-2.amazonaws.com/mongo-image-repository:client # todo-client
    container_name: todo-vue-client
    command: npm run serve
    depends_on:
      - server
    environment:
      - SERVERPORT=http://full-loadb-13v2jdptsmtfb-63353af261e3a4e6.elb.us-west-2.amazonaws.com:3001
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge
